vMainPath: "HallsHolicker"

vLdapConfig:
  vVersion: 2.5.7
  vDomain: example.com
  vLdapBaseDn: dc=example,dc=com
  vLdapServerOu : ou=ServerAdmin
  vLdapNetworkOu : ou=NetworkAdmin
  vLdapServer: "ldap://10.0.0.10/ ldap://10.0.0.20/"
  vLdapCertsDir: "/etc/pki/tls/"
  vRootPw: test1234
  vRootPwEncypt: "{SSHA}Th8aLQgQ5An7KdRbLJyFHixMb3QDCwUR"
  vBindDnPw: test5678
  vBindDnPwEncypt: "{SSHA}g/s1bmmnmiICbZNPn+fOVUwfalsfsihi"
  vMaster1IpAddress: "10.0.0.10"
  vMaster2IpAddress: "10.0.0.20"

vServerAdminUser:
  - { id: testuser1, uid: 1000, passwd: "{SSHA}rvzXGVTpeXEurL7YvosZ/H4wLrMoaeBw" }
  - { id: testuser2, uid: 1001, passwd: "{SSHA}uhh3/B81Xlrzj+FYgM9gRBSM1dQzCwHO" }

vNetworkAdminUser:
  - { id: testuser3, uid: 1000, passwd: "{SSHA}diEp52E9SYaRBDnG1zaA0QnSqutvGkNN" }
  - { id: testuser4, uid: 1001, passwd: "{SSHA}SGRoir2U9O2j1nIIPiXZaXKTSuIIzW71" }

vSudoUser:
  - testuser1
  - testuser2
  - testuser3

# 각 변수는 2자리를 유지 00 ~ 99
vPgchecker:
  uppercase: "02"         # 대문자
  lowercase: "06"         # 소문자
  digit: "02"             # 숫자
  special: "02"           # 특수문자

vAuditlogFile: openldap-auditlog.ldif