- name: Install SSSD
  yum:
    name: "{{ vLdapClientOs7Packages }}"
    state: present

- name: Make Directory {{ vLdapConfig.vLdapCertsDir }}
  file:
    path: "{{ vLdapConfig.vLdapCertsDir }}"
    state: directory

- name: Configure ldap.conf
  lineinfile:
    path: /etc/openldap/ldap.conf
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - "BASE  {{ vLdapConfig.vLdapServerOu }},{{ vLdapConfig.vLdapBaseDn }}"
    - "URI  {{ vLdapConfig.vLdapServer }}"
    - "sudoers_base ou=SUDOers,{{ vLdapConfig.vLdapBaseDn }}"

- name: Configure ldap.conf
  lineinfile:
    path: /etc/openldap/ldap.conf
    regexp: '^TLS_CACERTDIR(.*)'
    line: "TLS_CACERTDIR  {{ vLdapConfig.vLdapCertsDir }}"

- name: Update sssd.conf
  template:
    src: tSssd.conf.j2
    dest: /etc/sssd/sssd.conf

- name: Change mode & owner /etc/sssd/sssd.conf
  file:
    path: /etc/sssd/sssd.conf
    mode: 0600
    owner: root
    group: root

- name: Start & Enable oddjobd
  systemd:
    name: oddjobd
    state: restarted
    enabled: true
  
- name: Update the NSS and PAM configurations
  command: "authconfig --enablesssd --enablesssdauth --enablemkhomedir --update"

- name: Setting nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    line: "sudoers: sss ldap files"
    insertafter: EOF

- name: Start & Enable sssd
  systemd:
    name: sssd
    state: restarted
    enabled: true