- name: Import auditlogmodule.ldif
  copy:
    src: auditlogmodule.ldif
    dest: /etc/openldap/ldif/auditlogmodule.ldif

- name: Update OpenLDAP auditlogmodule.ldif
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/ldif/auditlogmodule.ldif"

- name: Import Auditlog.ldif
  template:
    src: tAuditlog.ldif.j2
    dest: /etc/openldap/ldif/Auditlog.ldif

- name: Update OpenLDAP Auditlog.ldif
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/ldif/Auditlog.ldif"